// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUscwqaHgo0NQpk6doYMlFVxtVFUNR95w',
    appId: '1:858086637078:web:add2d5dd9dd913276c7f37',
    messagingSenderId: '858086637078',
    projectId: 'noto-86e99',
    authDomain: 'noto-86e99.firebaseapp.com',
    storageBucket: 'noto-86e99.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdE1kod11JMa4cDAGk34IvqfT_tcL5CwM',
    appId: '1:858086637078:android:7cf1a276a6bf0f036c7f37',
    messagingSenderId: '858086637078',
    projectId: 'noto-86e99',
    storageBucket: 'noto-86e99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwVug4YToMZk0vabfKvN9Dpbtg9H2xVvY',
    appId: '1:858086637078:ios:4a0def50936930136c7f37',
    messagingSenderId: '858086637078',
    projectId: 'noto-86e99',
    storageBucket: 'noto-86e99.appspot.com',
    iosClientId: '858086637078-g9egjd2gs5j1agc0v0pafid6f2k8q7ps.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );
}
